vcf-split.o: vcf-split.c ../local/include/vcfio.h \
  ../local/include/dsvio.h ../local/include/biolibc.h \
  ../local/include/biostring.h ../local/include/xtendc.h \
  ../local/include/xtendc-protos.h vcf-split.h vcf-split-protos.h
	${CC} -c ${CFLAGS} vcf-split.c

