#!/bin/sh -ex

##########################################################################
#   Script description:
#       
#   History:
#   Date        Name        Modification
#   2019-12-08  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 multisample-VCF/BCF-file\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

# Filtering out calls with no het sites is probably useless with 137k
# samples per call.
# Does not seem to work in conjunction with --samples.
# --samples NWDXXXX --genotype het produces lines with 1|1 or 0|0.
# Maybe checking all samples for het instead of desired samples?
#
# vcftools is much slower than bcftools

# From bcf-bench:
# --min-ac + --genotype about double run time
# --min-ax + --samples increases run time by order of magnitude

time bcftools view --min-ac 2 --exclude-types indels \
    $1 | ./vcf-split --max-calls 100000 1 10

